export enum UploadedFileEnum {
  ASSETS_INVENTORY = 'ASSETS_INVENTORY',
  THREAT_ANALYSIS = 'THREAT_ANALYSIS',
  CURRENT_PROFILE = 'CURRENT_PROFILE',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  TARGET_PROFILE = 'TARGET_PROFILE',
  ACTIONS_PRIORITY = 'ACTIONS_PRIORITY',
  IMPLEMENTATION_DOC = 'IMPLEMENTATION_DOC'
}
